### ISSUE TITLE
installation doesn't pull down required dependencies

### ISSUE THREAD

**Issue by SensibleSalmon** [mmore500/templ#12]
fresh install of `templ` doesn't install the required `yaml` module
```sh
$ templ --help
Traceback (most recent call last):
  File "/usr/local/bin/templ", line 7, in <module>
    from templ.templ import main
  File "/usr/local/lib/python3.7/site-packages/templ/templ.py", line 17, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
```

much sad

**Comment by mmore500** [comment]
Good catch! Thanks for pointing that out, should be fixed now... yay for someone else installing templ for the first time ;)
